BEGIN TRANSACTION;

DROP TABLE IF EXISTS `TBL_USER`;
CREATE TABLE IF NOT EXISTS `TBL_USER` (
	`PK_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`TXT_userName`	TEXT NOT NULL,
	CONSTRAINT name_unique UNIQUE(`TXT_userName`)	
);
COMMIT;