BEGIN TRANSACTION;

DROP TABLE IF EXISTS `TBL_USER`;
DROP TABLE IF EXISTS 'sqlite_sequence';
CREATE TABLE IF NOT EXISTS `TBL_USER` (
	`PK_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`TXT_userName`	TEXT NOT NULL,
	CONSTRAINT name_unique UNIQUE(`TXT_userName`)	
);

CREATE TABLE sqlite_sequence(name,seq);

COMMIT;